[project]
name = "simple-social"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "allwyn46", email = "allwyn153@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi>=0.141.1",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "imagekitio>=5.9.0",
    "python-dotenv>=1.2.3",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
simple-social = "simple_social:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"


[tool.uv]
package = false
